image: python:3.8

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - Lint
  - Test
  - Build
  - Deploy

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r dev-requirements.txt

lint:
  stage: Lint
  allow_failure: true
  script:
    - flake8 amongus

# Run tests
test:
  stage: Test
  script:
    - python setup.py test

# Build package
build:
  stage: Build
  script:
    - python setup.py sdist bdist_wheel
  artifacts:
    paths:
      - dist

# Deploy package to TestPyPi
deploy:testpypi:
  stage: Deploy
  dependencies:
    - build
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $TESTPYPI_TOKEN
  script:
    - twine upload --repository testpypi dist/*

# Deploy package to PyPi
deploy:pypi:
  stage: Deploy
  dependencies:
    - build
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_TOKEN
  script:
    - twine upload dist/*
  only:
    - tags
